# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict

  # Quick syntax checkers
  - id: check-xml
  - id: check-yaml
  - id: check-toml
  - id: check-json

- repo: local
  hooks:
  - id: installer
    name: Regenerate Installer
    files: ".*\\.lua$"
    language: system
    pass_filenames: false
    entry: bin/mk-installer.lua
